universe       = docker
docker_image   = pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel

executable     = /bin/bash
arguments      = /home/YOUR_USERNAME/tml26-mia/run_job.sh

output         = /home/YOUR_USERNAME/tml26-mia/runlogs/mia.$(ClusterId).$(ProcId).out
error          = /home/YOUR_USERNAME/tml26-mia/runlogs/mia.$(ClusterId).$(ProcId).err
log            = /home/YOUR_USERNAME/tml26-mia/runlogs/mia.$(ClusterId).log

should_transfer_files = YES
stream_output = True
stream_error  = True

request_GPUs   = 1
request_CPUs   = 4
request_memory = 16G

requirements   = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted   = true
+WantScratchMounted   = true

queue 1